/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Clonable__factory } from "./ERC20Clonable__factory";
export { ForeignERC20__factory } from "./ForeignERC20__factory";
