/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as foreignErc20Sol from "./ForeignERC20.sol";
export type { foreignErc20Sol };
import type * as foreignErc721Sol from "./ForeignERC721.sol";
export type { foreignErc721Sol };
import type * as testing from "./testing";
export type { testing };
export type { ERC20Holder } from "./ERC20Holder";
export type { ERC721Holder } from "./ERC721Holder";
export type { ETHHolder } from "./ETHHolder";
export type { Erdstall } from "./Erdstall";
export type { ForeignAsset } from "./ForeignAsset";
export type { ForeignAssetHolder } from "./ForeignAssetHolder";
export type { PerunToken } from "./PerunToken";
export type { TokenHolder } from "./TokenHolder";
