/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BehaviorSelectInterface extends Interface {
  getFunction(
    nameOrSignature: "reset" | "setMode" | "setModeWithCountdown"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setModeWithCountdown",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setModeWithCountdown",
    data: BytesLike
  ): Result;
}

export interface BehaviorSelect extends BaseContract {
  connect(runner?: ContractRunner | null): BehaviorSelect;
  waitForDeployment(): Promise<this>;

  interface: BehaviorSelectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reset: TypedContractMethod<[], [void], "nonpayable">;

  setMode: TypedContractMethod<[mode_: BigNumberish], [void], "nonpayable">;

  setModeWithCountdown: TypedContractMethod<
    [
      before_: BigNumberish,
      countdown_: BigNumberish,
      after_: BigNumberish,
      resetCount_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMode"
  ): TypedContractMethod<[mode_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setModeWithCountdown"
  ): TypedContractMethod<
    [
      before_: BigNumberish,
      countdown_: BigNumberish,
      after_: BigNumberish,
      resetCount_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
