/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BehaviorSelect } from "./BehaviorSelect";
export type { ContractBasedUser } from "./ContractBasedUser";
export type { ERC20TestToken } from "./ERC20TestToken";
export type { ERC721TestToken } from "./ERC721TestToken";
export type { MockErdstall } from "./MockErdstall";
