/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Erdstall {
  export type AssetStruct = {
    origin: BigNumberish;
    assetType: BigNumberish;
    localID: BytesLike;
  };

  export type AssetStructOutput = [
    origin: bigint,
    assetType: bigint,
    localID: string
  ] & { origin: bigint; assetType: bigint; localID: string };

  export type TokenValueStruct = {
    asset: Erdstall.AssetStruct;
    value: BigNumberish[];
  };

  export type TokenValueStructOutput = [
    asset: Erdstall.AssetStructOutput,
    value: bigint[]
  ] & { asset: Erdstall.AssetStructOutput; value: bigint[] };

  export type BalanceChunkStruct = {
    epoch: BigNumberish;
    id: BigNumberish;
    count: BigNumberish;
    chain: BigNumberish;
    account: AddressLike;
    exit: boolean;
    tokens: Erdstall.TokenValueStruct[];
  };

  export type BalanceChunkStructOutput = [
    epoch: bigint,
    id: bigint,
    count: bigint,
    chain: bigint,
    account: string,
    exit: boolean,
    tokens: Erdstall.TokenValueStructOutput[]
  ] & {
    epoch: bigint;
    id: bigint;
    count: bigint;
    chain: bigint;
    account: string;
    exit: boolean;
    tokens: Erdstall.TokenValueStructOutput[];
  };

  export type ZeroBalanceProofStruct = {
    epoch: BigNumberish;
    chain: BigNumberish;
    account: AddressLike;
  };

  export type ZeroBalanceProofStructOutput = [
    epoch: bigint,
    chain: bigint,
    account: string
  ] & { epoch: bigint; chain: bigint; account: string };

  export type FreezeProofStruct = {
    chain: BigNumberish;
    block: BigNumberish;
    epoch: BigNumberish;
  };

  export type FreezeProofStructOutput = [
    chain: bigint,
    block: bigint,
    epoch: bigint
  ] & { chain: bigint; block: bigint; epoch: bigint };
}

export interface MockErdstallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bigBangTime"
      | "chainID"
      | "challenge"
      | "challenges"
      | "deployBlockNum"
      | "deposit"
      | "deposits"
      | "encodeBalanceProof"
      | "ensureFrozen"
      | "epochDuration"
      | "frozenEpoch"
      | "holderTypes"
      | "invokeTransfer"
      | "metadataWasHandled"
      | "numChallenges"
      | "owner"
      | "registerTokenType"
      | "renounceOwnership"
      | "respondChallenge"
      | "respondZero"
      | "submitFreezeProof"
      | "tee"
      | "tokenHolders"
      | "transferOwnership"
      | "verifyBalance"
      | "verifyLightClientCert"
      | "verifyTeeSig"
      | "withdraw"
      | "withdrawFrozen"
      | "withdrawFrozenDeposit"
      | "withdrawn"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeResponded"
      | "Challenged"
      | "Deposited"
      | "FirstTimeFungible"
      | "FirstTimeNFT"
      | "Frozen"
      | "OwnershipTransferred"
      | "TokenTypeRegistered"
      | "WithdrawalException"
      | "Withdrawn"
      | "ZeroResponded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bigBangTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chainID", values?: undefined): string;
  encodeFunctionData(functionFragment: "challenge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "challenges",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployBlockNum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeBalanceProof",
    values: [Erdstall.BalanceChunkStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ensureFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "frozenEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "holderTypes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invokeTransfer",
    values: [AddressLike, BigNumberish, BytesLike, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "metadataWasHandled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "numChallenges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerTokenType",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "respondChallenge",
    values: [Erdstall.BalanceChunkStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "respondZero",
    values: [Erdstall.ZeroBalanceProofStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFreezeProof",
    values: [Erdstall.FreezeProofStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenHolders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBalance",
    values: [Erdstall.BalanceChunkStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLightClientCert",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTeeSig",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [Erdstall.BalanceChunkStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFrozen",
    values: [Erdstall.BalanceChunkStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFrozenDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawn",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bigBangTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployBlockNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "encodeBalanceProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ensureFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invokeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataWasHandled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerTokenType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondZero",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFreezeProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLightClientCert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTeeSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFrozenDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdrawn", data: BytesLike): Result;
}

export namespace ChallengeRespondedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    account: AddressLike,
    id: BigNumberish,
    count: BigNumberish,
    tokens: Erdstall.TokenValueStruct[],
    exit: boolean,
    sig: BytesLike
  ];
  export type OutputTuple = [
    epoch: bigint,
    account: string,
    id: bigint,
    count: bigint,
    tokens: Erdstall.TokenValueStructOutput[],
    exit: boolean,
    sig: string
  ];
  export interface OutputObject {
    epoch: bigint;
    account: string;
    id: bigint;
    count: bigint;
    tokens: Erdstall.TokenValueStructOutput[];
    exit: boolean;
    sig: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengedEvent {
  export type InputTuple = [epoch: BigNumberish, account: AddressLike];
  export type OutputTuple = [epoch: bigint, account: string];
  export interface OutputObject {
    epoch: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    account: AddressLike,
    value: Erdstall.TokenValueStruct
  ];
  export type OutputTuple = [
    epoch: bigint,
    account: string,
    value: Erdstall.TokenValueStructOutput
  ];
  export interface OutputObject {
    epoch: bigint;
    account: string;
    value: Erdstall.TokenValueStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstTimeFungibleEvent {
  export type InputTuple = [
    localID: BytesLike,
    name: string,
    symbol: string,
    decimals: BigNumberish
  ];
  export type OutputTuple = [
    localID: string,
    name: string,
    symbol: string,
    decimals: bigint
  ];
  export interface OutputObject {
    localID: string;
    name: string;
    symbol: string;
    decimals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstTimeNFTEvent {
  export type InputTuple = [
    localID: BytesLike,
    name: string,
    symbol: string,
    sampleURI: string
  ];
  export type OutputTuple = [
    localID: string,
    name: string,
    symbol: string,
    sampleURI: string
  ];
  export interface OutputObject {
    localID: string;
    name: string;
    symbol: string;
    sampleURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FrozenEvent {
  export type InputTuple = [epoch: BigNumberish];
  export type OutputTuple = [epoch: bigint];
  export interface OutputObject {
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenTypeRegisteredEvent {
  export type InputTuple = [assetType: BigNumberish, tokenHolder: AddressLike];
  export type OutputTuple = [assetType: bigint, tokenHolder: string];
  export interface OutputObject {
    assetType: bigint;
    tokenHolder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalExceptionEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    account: AddressLike,
    token: Erdstall.TokenValueStruct,
    error: BytesLike
  ];
  export type OutputTuple = [
    epoch: bigint,
    account: string,
    token: Erdstall.TokenValueStructOutput,
    error: string
  ];
  export interface OutputObject {
    epoch: bigint;
    account: string;
    token: Erdstall.TokenValueStructOutput;
    error: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    account: AddressLike,
    tokens: Erdstall.TokenValueStruct[]
  ];
  export type OutputTuple = [
    epoch: bigint,
    account: string,
    tokens: Erdstall.TokenValueStructOutput[]
  ];
  export interface OutputObject {
    epoch: bigint;
    account: string;
    tokens: Erdstall.TokenValueStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZeroRespondedEvent {
  export type InputTuple = [epoch: BigNumberish, account: AddressLike];
  export type OutputTuple = [epoch: bigint, account: string];
  export interface OutputObject {
    epoch: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockErdstall extends BaseContract {
  connect(runner?: ContractRunner | null): MockErdstall;
  waitForDeployment(): Promise<this>;

  interface: MockErdstallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bigBangTime: TypedContractMethod<[], [bigint], "view">;

  chainID: TypedContractMethod<[], [bigint], "view">;

  challenge: TypedContractMethod<[], [void], "nonpayable">;

  challenges: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  deployBlockNum: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [
      depositor: AddressLike,
      assetType: BigNumberish,
      origin: BigNumberish,
      token: BytesLike,
      value: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  deposits: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [Erdstall.AssetStructOutput],
    "view"
  >;

  encodeBalanceProof: TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct],
    [string],
    "view"
  >;

  ensureFrozen: TypedContractMethod<[], [void], "nonpayable">;

  epochDuration: TypedContractMethod<[], [bigint], "view">;

  frozenEpoch: TypedContractMethod<[], [bigint], "view">;

  holderTypes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  invokeTransfer: TypedContractMethod<
    [
      holder: AddressLike,
      origin: BigNumberish,
      localID: BytesLike,
      recipient: AddressLike,
      value: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  metadataWasHandled: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  numChallenges: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerTokenType: TypedContractMethod<
    [holder: AddressLike, localTokenType: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  respondChallenge: TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;

  respondZero: TypedContractMethod<
    [proof: Erdstall.ZeroBalanceProofStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;

  submitFreezeProof: TypedContractMethod<
    [proof: Erdstall.FreezeProofStruct, sig: BytesLike, certificate: BytesLike],
    [void],
    "nonpayable"
  >;

  tee: TypedContractMethod<[], [string], "view">;

  tokenHolders: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyBalance: TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "view"
  >;

  verifyLightClientCert: TypedContractMethod<
    [lightClient: AddressLike, certificate: BytesLike],
    [void],
    "view"
  >;

  verifyTeeSig: TypedContractMethod<
    [abiCode: BytesLike, sig: BytesLike],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawFrozen: TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawFrozenDeposit: TypedContractMethod<[], [void], "nonpayable">;

  withdrawn: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bigBangTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challenge"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployBlockNum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      depositor: AddressLike,
      assetType: BigNumberish,
      origin: BigNumberish,
      token: BytesLike,
      value: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [Erdstall.AssetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "encodeBalanceProof"
  ): TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "ensureFrozen"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "epochDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "frozenEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "holderTypes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "invokeTransfer"
  ): TypedContractMethod<
    [
      holder: AddressLike,
      origin: BigNumberish,
      localID: BytesLike,
      recipient: AddressLike,
      value: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "metadataWasHandled"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "numChallenges"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerTokenType"
  ): TypedContractMethod<
    [holder: AddressLike, localTokenType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "respondChallenge"
  ): TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "respondZero"
  ): TypedContractMethod<
    [proof: Erdstall.ZeroBalanceProofStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitFreezeProof"
  ): TypedContractMethod<
    [proof: Erdstall.FreezeProofStruct, sig: BytesLike, certificate: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenHolders"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyBalance"
  ): TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyLightClientCert"
  ): TypedContractMethod<
    [lightClient: AddressLike, certificate: BytesLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTeeSig"
  ): TypedContractMethod<
    [abiCode: BytesLike, sig: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFrozen"
  ): TypedContractMethod<
    [balance: Erdstall.BalanceChunkStruct, sig: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFrozenDeposit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawn"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ChallengeResponded"
  ): TypedContractEvent<
    ChallengeRespondedEvent.InputTuple,
    ChallengeRespondedEvent.OutputTuple,
    ChallengeRespondedEvent.OutputObject
  >;
  getEvent(
    key: "Challenged"
  ): TypedContractEvent<
    ChallengedEvent.InputTuple,
    ChallengedEvent.OutputTuple,
    ChallengedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "FirstTimeFungible"
  ): TypedContractEvent<
    FirstTimeFungibleEvent.InputTuple,
    FirstTimeFungibleEvent.OutputTuple,
    FirstTimeFungibleEvent.OutputObject
  >;
  getEvent(
    key: "FirstTimeNFT"
  ): TypedContractEvent<
    FirstTimeNFTEvent.InputTuple,
    FirstTimeNFTEvent.OutputTuple,
    FirstTimeNFTEvent.OutputObject
  >;
  getEvent(
    key: "Frozen"
  ): TypedContractEvent<
    FrozenEvent.InputTuple,
    FrozenEvent.OutputTuple,
    FrozenEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenTypeRegistered"
  ): TypedContractEvent<
    TokenTypeRegisteredEvent.InputTuple,
    TokenTypeRegisteredEvent.OutputTuple,
    TokenTypeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalException"
  ): TypedContractEvent<
    WithdrawalExceptionEvent.InputTuple,
    WithdrawalExceptionEvent.OutputTuple,
    WithdrawalExceptionEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ZeroResponded"
  ): TypedContractEvent<
    ZeroRespondedEvent.InputTuple,
    ZeroRespondedEvent.OutputTuple,
    ZeroRespondedEvent.OutputObject
  >;

  filters: {
    "ChallengeResponded(uint64,address,uint32,uint32,tuple[],bool,bytes)": TypedContractEvent<
      ChallengeRespondedEvent.InputTuple,
      ChallengeRespondedEvent.OutputTuple,
      ChallengeRespondedEvent.OutputObject
    >;
    ChallengeResponded: TypedContractEvent<
      ChallengeRespondedEvent.InputTuple,
      ChallengeRespondedEvent.OutputTuple,
      ChallengeRespondedEvent.OutputObject
    >;

    "Challenged(uint64,address)": TypedContractEvent<
      ChallengedEvent.InputTuple,
      ChallengedEvent.OutputTuple,
      ChallengedEvent.OutputObject
    >;
    Challenged: TypedContractEvent<
      ChallengedEvent.InputTuple,
      ChallengedEvent.OutputTuple,
      ChallengedEvent.OutputObject
    >;

    "Deposited(uint64,address,tuple)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "FirstTimeFungible(bytes32,string,string,uint8)": TypedContractEvent<
      FirstTimeFungibleEvent.InputTuple,
      FirstTimeFungibleEvent.OutputTuple,
      FirstTimeFungibleEvent.OutputObject
    >;
    FirstTimeFungible: TypedContractEvent<
      FirstTimeFungibleEvent.InputTuple,
      FirstTimeFungibleEvent.OutputTuple,
      FirstTimeFungibleEvent.OutputObject
    >;

    "FirstTimeNFT(bytes32,string,string,string)": TypedContractEvent<
      FirstTimeNFTEvent.InputTuple,
      FirstTimeNFTEvent.OutputTuple,
      FirstTimeNFTEvent.OutputObject
    >;
    FirstTimeNFT: TypedContractEvent<
      FirstTimeNFTEvent.InputTuple,
      FirstTimeNFTEvent.OutputTuple,
      FirstTimeNFTEvent.OutputObject
    >;

    "Frozen(uint64)": TypedContractEvent<
      FrozenEvent.InputTuple,
      FrozenEvent.OutputTuple,
      FrozenEvent.OutputObject
    >;
    Frozen: TypedContractEvent<
      FrozenEvent.InputTuple,
      FrozenEvent.OutputTuple,
      FrozenEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenTypeRegistered(uint8,address)": TypedContractEvent<
      TokenTypeRegisteredEvent.InputTuple,
      TokenTypeRegisteredEvent.OutputTuple,
      TokenTypeRegisteredEvent.OutputObject
    >;
    TokenTypeRegistered: TypedContractEvent<
      TokenTypeRegisteredEvent.InputTuple,
      TokenTypeRegisteredEvent.OutputTuple,
      TokenTypeRegisteredEvent.OutputObject
    >;

    "WithdrawalException(uint64,address,tuple,bytes)": TypedContractEvent<
      WithdrawalExceptionEvent.InputTuple,
      WithdrawalExceptionEvent.OutputTuple,
      WithdrawalExceptionEvent.OutputObject
    >;
    WithdrawalException: TypedContractEvent<
      WithdrawalExceptionEvent.InputTuple,
      WithdrawalExceptionEvent.OutputTuple,
      WithdrawalExceptionEvent.OutputObject
    >;

    "Withdrawn(uint64,address,tuple[])": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "ZeroResponded(uint64,address)": TypedContractEvent<
      ZeroRespondedEvent.InputTuple,
      ZeroRespondedEvent.OutputTuple,
      ZeroRespondedEvent.OutputObject
    >;
    ZeroResponded: TypedContractEvent<
      ZeroRespondedEvent.InputTuple,
      ZeroRespondedEvent.OutputTuple,
      ZeroRespondedEvent.OutputObject
    >;
  };
}
