/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IERC721Minter } from "../IERC721Minter";

export class IERC721Minter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Minter {
    return new Contract(address, _abi, signerOrProvider) as IERC721Minter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
