/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { TokenHolder, TokenHolderInterface } from "../TokenHolder";

const _abi = [
  {
    inputs: [],
    name: "erdstall",
    outputs: [
      {
        internalType: "contract Erdstall",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "value",
        type: "bytes",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenHolder__factory {
  static readonly abi = _abi;
  static createInterface(): TokenHolderInterface {
    return new utils.Interface(_abi) as TokenHolderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenHolder {
    return new Contract(address, _abi, signerOrProvider) as TokenHolder;
  }
}
